image: node:6.9.4

clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - node
          - sonarcloud
          - node-scanner
        script: 
          - npm install -g sonarqube-scanner
          - sonar-scanner -Dsonar.login=$SONAR_TOKEN

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    node-scanner: ~/.sonar/native-sonar-scanner