image: node:6.9.4

clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - node
          - sonarcloud
          - node-scanner
        script: 
          - npm install -g sonarqube-scanner
          - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=basrieter-bitbucket -Dsonar.projectKey=basrieter_xbmc-online-tv -Dsonar.login=$SONAR_TOKEN -Dsonar.sources=. 

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    node-scanner: ~/.sonar/native-sonar-scanner